services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password_mongo"
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password_mongo"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "password_express"
  web:
    build: .
    image: weather_app:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: "admin"
      MONGO_PASSWORD: "password_mongo"
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "weather_db"

volumes:
  mongo-data:
    driver: local
